### PR TITLE
Created a data model

### PR DESCRIPTION
**Pull request by alphayowakarindi**
At this juncture of development I implemented the following:
- Created `User` model and `users` migration.
- Created `Post` model, `posts` migration and the association of post with authors.
- Created `Like` model, `likess` migration and the association of likes with authors and posts.
- Created `Comment` model, `comments` migration and the association of comments with authors and posts.
- Ran all the migrations.

### CODE REVIEW

**Comment by sja-thedude** [comment]
Hi @alphayowakarindi ,

You don't have a professional readme and have not added linters. If you could add both in 10 mins then I will proceed else invalidate it.

**Comment by alphayowakarindi** [comment]
Hi @sja-thedude, thank you so much for taking the time to leave this excellent review. Fixing that now.

**Comment by sja-thedude** [comment]
@alphayowakarindi Could you make it fast?

**Comment by sja-thedude** [comment]
@alphayowakarindi Could you make it fast? Adding the Professional Readme.....

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @alphayowakarindi, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All linters passing
- All requirements completed
- Professional readme

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alphayowakarindi** [comment]
@sja-thedude I appreciate your patience and input to make my code better. Cheers!

**Pull request merged**
